---
- name: test playbook
  hosts: webservers
  become: true
  gather_facts: true

  tasks:
    - name: copy files from host to nodes
      copy:
        src: /home/ansible/newfile
        dest: /tmp
