---
- name: test playbook
  hosts: webservers
  become: true
  user: ansible

  tasks:
    - name: creating a file 
      file:
        path: /home/ansible/megafile.txt
        state: touch

    - name: creating a directory
      file:
        path: /home/ansible/megadir
        state: directory
